project:
  type: website
  output-dir: C:/Users/joselyn7.stu/OneDrive - UBC/Documents/GitHub/E-Portfolio

website:
  title: "Joselyne MPAYIMANA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: publications.qmd
        text: Publications
      - href: content.qmd
        text: Content & Deliverables
      
      

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

editor: visual

